### ISSUE TITLE
Building on newest MSVC-x64 compiler fails

### ISSUE THREAD

**Issue by nshtg** [alexcrichton/curl-rust#152]
I just created an empty project with just curl-rust as dependency and tried to compile it, leading to this error.

Version:
```nightly-x86_64-pc-windows-msvc unchanged - rustc 1.17.0-nightly (b1e31766d 2017-03-03)```

Error log:
```
$ RUST_BACKTRACE=1 cargo build --verbose
   Compiling libc v0.2.21
   Compiling winapi v0.2.8
   Compiling gcc v0.3.43
   Compiling pkg-config v0.3.9
     Running `rustc --crate-name libc 'C:\Users\frk\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.21\src\lib.rs' --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="use_std"' --cfg 'feature="default"' -C metadata=5dc7b85e748840b4 -C extra-filename=-5dc7b85e748840b4 --out-dir 'Y:\Develop\Rust\testd\target\debug\deps' -L 'dependency=Y:\Develop\Rust\testd\target\debug\deps' --cap-lints allow`
     Running `rustc --crate-name winapi 'C:\Users\frk\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.8\src\lib.rs' --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=a5898d7aceb63fac -C extra-filename=-a5898d7aceb63fac --out-dir 'Y:\Develop\Rust\testd\target\debug\deps' -L 'dependency=Y:\Develop\Rust\testd\target\debug\deps' --cap-lints allow`
     Running `rustc --crate-name gcc 'C:\Users\frk\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.43\src\lib.rs' --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=1cbfaa684f6fc20f -C extra-filename=-1cbfaa684f6fc20f --out-dir 'Y:\Develop\Rust\testd\target\debug\deps' -L 'dependency=Y:\Develop\Rust\testd\target\debug\deps' --cap-lints allow`
     Running `rustc --crate-name pkg_config 'C:\Users\frk\.cargo\registry\src\github.com-1ecc6299db9ec823\pkg-config-0.3.9\src\lib.rs' --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=af8168308ca6d27e -C extra-filename=-af8168308ca6d27e --out-dir 'Y:\Develop\Rust\testd\target\debug\deps' -L 'dependency=Y:\Develop\Rust\testd\target\debug\deps' --cap-lints allow`
   Compiling libz-sys v1.0.13
   Compiling curl-sys v0.3.10
     Running `rustc --crate-name build_script_build 'C:\Users\frk\.cargo\registry\src\github.com-1ecc6299db9ec823\libz-sys-1.0.13\build.rs' --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=7f753eb014383b82 -C extra-filename=-7f753eb014383b82 --out-dir 'Y:\Develop\Rust\testd\target\debug\build\libz-sys-7f753eb014383b82' -L 'dependency=Y:\Develop\Rust\testd\target\debug\deps' --extern 'gcc=Y:\Develop\Rust\testd\target\debug\deps\libgcc-1cbfaa684f6fc20f.rlib' --extern 'pkg_config=Y:\Develop\Rust\testd\target\debug\deps\libpkg_config-af8168308ca6d27e.rlib' --cap-lints allow`
     Running `rustc --crate-name build_script_build 'C:\Users\frk\.cargo\registry\src\github.com-1ecc6299db9ec823\curl-sys-0.3.10\build.rs' --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=2f89535e15ff36f6 -C extra-filename=-2f89535e15ff36f6 --out-dir 'Y:\Develop\Rust\testd\target\debug\build\curl-sys-2f89535e15ff36f6' -L 'dependency=Y:\Develop\Rust\testd\target\debug\deps' --extern 'gcc=Y:\Develop\Rust\testd\target\debug\deps\libgcc-1cbfaa684f6fc20f.rlib' --extern 'pkg_config=Y:\Develop\Rust\testd\target\debug\deps\libpkg_config-af8168308ca6d27e.rlib' --cap-lints allow`
     Running `Y:\Develop\Rust\testd\target\debug\build\libz-sys-7f753eb014383b82\build-script-build`
     Running `rustc --crate-name libz_sys 'C:\Users\frk\.cargo\registry\src\github.com-1ecc6299db9ec823\libz-sys-1.0.13\src\lib.rs' --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=b34e05ee2e9e1468 -C extra-filename=-b34e05ee2e9e1468 --out-dir 'Y:\Develop\Rust\testd\target\debug\deps' -L 'dependency=Y:\Develop\Rust\testd\target\debug\deps' --extern 'libc=Y:\Develop\Rust\testd\target\debug\deps\liblibc-5dc7b85e748840b4.rlib' --cap-lints allow -L 'Y:\Develop\Rust\testd\target\debug\build\libz-sys-3f97c24ccab6f5c7\out/lib' -l static=zlib`
     Running `Y:\Develop\Rust\testd\target\debug\build\curl-sys-2f89535e15ff36f6\build-script-build`
error: failed to run custom build command for `curl-sys v0.3.10`
process didn't exit successfully: `Y:\Develop\Rust\testd\target\debug\build\curl-sys-2f89535e15ff36f6\build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=Y:\Develop\Rust\testd\target\debug\build\curl-sys-500ff2f52156f2b8\out/lib
cargo:rustc-link-lib=static=curl
cargo:root=Y:\Develop\Rust\testd\target\debug\build\curl-sys-500ff2f52156f2b8\out
cargo:include=Y:\Develop\Rust\testd\target\debug\build\curl-sys-500ff2f52156f2b8\out/include
cargo:rustc-link-lib=ws2_32
cargo:rustc-link-lib=crypt32

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at 'fs::hard_link(inc.join("lib/zlib.lib"), inc.join("lib/zlib_a.lib")) return the error Incorrect function. (os error 1)', C:\Users\frk\.cargo\registry\src\github.com-1ecc6299db9ec823\curl-sys-0.3.10\build.rs:302
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: build_script_build::build_msvc
             at ./build.rs:302
   1: build_script_build::main
             at ./build.rs:66
```

**Comment by nshtg** [comment]
I found what is causing this error: Seems like ```exFAT``` does not support hard or soft links.

Maybe we could copy or move the ```zlib.lib``` if creating a symlink fails?
