### ISSUE TITLE
Building on MSVC compiler fails

### ISSUE THREAD

**Issue by pravic** [alexcrichton/curl-rust#168]
```
thread 'main' panicked at 'fs::copy(libs.join("lib/libcurl_a.lib"), dst.join("lib/curl.lib")) return the error (os error 3)', build.rs:334
stack backtrace:
   0:  0x106a260 - std::panicking::default_hook::{{closure}}
                       at C:\projects\rust\src\libstd\panicking.rs:354
   1:  0x1069d7c - std::panicking::default_hook
                       at C:\projects\rust\src\libstd\panicking.rs:371
   2:  0x106a787 - std::panicking::rust_panic_with_hook
                       at C:\projects\rust\src\libstd\panicking.rs:549
   3:  0x106a647 - std::panicking::begin_panic<collections::string::String>
                       at C:\projects\rust\src\libstd\panicking.rs:511
   4:  0x106a587 - std::panicking::begin_panic_fmt
                       at C:\projects\rust\src\libstd\panicking.rs:495
   5:   0xfdc9ce - build_script_build::build_msvc
                       at c:\Windows\Temp\curl-sys\build.rs:334
   6:   0xfd796d - build_script_build::main
                       at c:\Windows\Temp\curl-sys\build.rs:72
   7:  0x106c0cb - panic_unwind::__rust_maybe_catch_panic
                       at C:\projects\rust\src\libpanic_unwind\lib.rs:98
   8:  0x106addd - std::rt::lang_start
                       at C:\projects\rust\src\libstd\rt.rs:51
   9:   0xfde821 - main
  10:  0x10725a3 - __scrt_common_main_seh
                       at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  11: 0x74ec3379 - BaseThreadInitThunk
  12: 0x770e92e1 - __RtlUserThreadStart
```

```
curl-sys>ls curl\builds
libcurl-vc-x86-release-static-ipv6-sspi-winssl
libcurl-vc-x86-release-static-ipv6-sspi-winssl-obj-curl
libcurl-vc-x86-release-static-ipv6-sspi-winssl-obj-lib

curl-sys>ls curl\builds\libcurl-vc-x86-release-static-ipv6-sspi-winssl
bin  include  lib
```

~Apparently curl has changed the output directory name.~ This issue is unrelated to #152.

Update: No, this name is handled in build.rs. No idea why it fails then :(

**Comment by pravic** [comment]
> No idea why it fails then
Apparently because `src.join("curl/builds").join(name)` expands to 
`libcurl-vc-x86-release-static-zlib-static-ipv6-sspi-winssl` instead of
`libcurl-vc-x86-release-static-ipv6-sspi-winssl`.

P.S. `static-zlib-static`?

**Comment by pravic** [comment]
Looks like fixed. Checked with stable and nightly (622e7e648 2017-06-21) rustc.

**Comment by alexcrichton** [comment]
Ok!
