### ISSUE TITLE
post tests are failing

### ISSUE THREAD

**Issue by ignatenkobrain** [alexcrichton/curl-rust#196]
```rust
thread '<unnamed>' panicked at 'unexpected header: "--------------------------6309201c6c4c865b\r\n" (remaining headers {"Expect: 100-continue\r\n"})', tests/server/mod.rs:64:20thread '
<unnamed>note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '' panicked at '<unnamed>unexpected header: "--------------------------7a824581ea3ed913\r\n" (remaining headers {"Expect: 100-continue\r\n"})' panicked at '', unexpected header: "--------------------------38fff97e24d6ce42\r\n" (remaining headers {"Expect: 100-continue\r\n"})tests/server/mod.rs', :tests/server/mod.rs64::6420:
20
test buffer ... FAILED
test custom ... FAILED
test file ... FAILED

failures:

---- buffer stdout ----
	thread 'buffer' panicked at 'handle.perform() failed with Error { description: "Server returned nothing (no headers, no data)", code: 52, extra: Some("Empty reply from server") }', tests/post.rs:77:4
child server thread also failed: Any

---- custom stdout ----
	thread 'custom' panicked at 'handle.perform() failed with Error { description: "Server returned nothing (no headers, no data)", code: 52, extra: Some("Empty reply from server") }', tests/post.rs:47:4
child server thread also failed: Any

---- file stdout ----
	thread 'file' panicked at 'handle.perform() failed with Error { description: "Server returned nothing (no headers, no data)", code: 52, extra: Some("Empty reply from server") }', tests/post.rs:108:4
child server thread also failed: Any


failures:
    buffer
    custom
    file

```

Not sure how to debug..

**Comment by hhatto** [comment]
Hi,
I have same error on libcurl version 7.58.0.
Depending on the version of libcurl, the Expect header may not be added in some cases.

You can avoid it with the following changes:
https://github.com/hhatto/curl-rust/commit/1cdfd6afd97f66db1f9ff0d8962130f3eb5ed2f9

**Comment by alexcrichton** [comment]
I think this should be fixed now!
