### ISSUE TITLE
Doesn't support windows gnu build with cygwin

### ISSUE THREAD

**Issue by Dragonrun1** [alexcrichton/curl-rust#215]
```
   Compiling pkg-config v0.3.11
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling cc v1.0.17
   Compiling winapi v0.3.5
   Compiling libc v0.2.42
   Compiling libz-sys v1.0.18
   Compiling curl-sys v0.4.5
error: failed to run custom build command for `curl-sys v0.4.5`
process didn't exit successfully: `C:\repos\Github\djb_hash\target\debug\build\curl-sys-6f652049533326d5\build-sc
ript-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=C:\repos\Github\djb_hash\target\debug\build\curl-sys-4bc325cb3b0b94cc\out/lib
cargo:rustc-link-lib=static=curl
cargo:root=C:\repos\Github\djb_hash\target\debug\build\curl-sys-4bc325cb3b0b94cc\out
cargo:include=C:\repos\Github\djb_hash\target\debug\build\curl-sys-4bc325cb3b0b94cc\out/include
cargo:rustc-link-lib=ws2_32
cargo:rustc-link-lib=crypt32
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "sh" "/c/Users/Dragonaire/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.4.5/curl/configure"
 "--with-winssl" "--enable-static=yes" "--enable-shared=no" "--enable-debug" "--disable-optimize" "--prefix=/c/re
pos/Github/djb_hash/target/debug/build/curl-sys-4bc325cb3b0b94cc/out" "--without-nghttp2" "--without-librtmp" "--
without-libidn2" "--without-libssh2" "--without-libpsl" "--disable-ldap" "--disable-ldaps" "--disable-ftp" "--dis
able-rtsp" "--disable-dict" "--disable-telnet" "--disable-tftp" "--disable-pop3" "--disable-imap" "--disable-smtp
" "--disable-gopher" "--disable-manual" "--disable-smb" "--disable-sspi" "--disable-manual" "--disable-unix-socke
ts" "--disable-versioned-symbols" "--enable-hidden-symbols" "--disable-libcurl-option"

--- stderr
fatal: not a git repository (or any parent up to mount point /cygdrive)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/usr/bin/sh: /c/Users/Dragonaire/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.4.5/curl/configure: N
o such file or directory
thread 'main' panicked at '
command did not execute successfully, got: exit code: 127

build script failed, must exit now', C:\Users\Dragonaire\.cargo\registry\src\github.com-1ecc6299db9ec823\curl-sys
-0.4.5\build.rs:224:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at libstd\sys\windows\backtrace/mod.rs:65
   1: std::sys_common::backtrace::print
             at libstd\sys_common/backtrace.rs:71
             at libstd\sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   7: build_script_build::fail
             at .\build.rs:224
   8: build_script_build::run
             at .\build.rs:219
   9: build_script_build::main
             at .\build.rs:199
  10: std::rt::lang_start::{{closure}}
             at C:\projects\rust\src\libstd/rt.rs:74
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: _rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::panic::catch_unwind
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
  14: std::rt::lang_start_internal
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at C:\projects\rust\src\libstd/rt.rs:74
  16: main
  17: _tmainCRTStartup
  18: mainCRTStartup
  19: unit_addrs_search
  20: unit_addrs_search

warning: build failed, waiting for other jobs to finish...
error: build failed
```

For me MSVC builds are flaky at best with even minor updates to VS causing them to break but all of my projects just work with cygwin. Could we get a build that works with it instead or in addition to the MSVC version?

**Comment by alexcrichton** [comment]
The error message here is:

```
/usr/bin/sh: /c/Users/Dragonaire/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.4.5/curl/configure: No such file or directory
```

Do you know why that might be?

**Comment by Dragonrun1** [comment]
Not sure I know I have curl and its dev stuff installed so not sure why it doesn't find it

**Comment by alexcrichton** [comment]
I'm going to close this since the build system has drastrically changed since this was opened.
