### ISSUE TITLE
Multiple tests are failing

### ISSUE THREAD

**Issue by ignatenkobrain** [alexcrichton/curl-rust#219]
```
     Running `/usr/share/cargo/registry/curl-0.4.12/target/release/deps/curl-0f0993e938af1206`

running 3 tests
test easy::handler::double_seconds_to_duration_sub_second1 ... ok
test easy::handler::double_seconds_to_duration_sub_second2 ... ok
test easy::handler::double_seconds_to_duration_whole_second ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running `/usr/share/cargo/registry/curl-0.4.12/target/release/deps/easy-212dc3b6549f7366`

running 29 tests
test noproxy ... ignored
test misc ... ok
test check_unix_socket ... ok
test perform_in_perform_is_bad ... ok
test headers ... ok
test get_path ... ok
test accept_encoding ... ok
test cookie ... ok
test getters ... ok
test get_smoke ... ok
test abort_read ... ok
test post3 ... ok
test follow_location ... ok
test progress ... ok
test panic_in_callback ... ok
test pause_write_then_resume ... ok
test post1 ... ok
test post2 ... ok
test write_callback ... ok
test url_encoding ... ok
test userpass ... ok
test put ... ok
test proxy ... ok
test resolve ... ok
test referer ... ok
test useragent ... ok
test custom_headers ... ok
test fail_on_error ... ok
test port ... ok

test result: ok. 28 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out

     Running `/usr/share/cargo/registry/curl-0.4.12/target/release/deps/multi-021f2f1ce85c316a`

running 4 tests
test waitfds ... ok
test smoke ... ok
test smoke2 ... ok
test upload_lots ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running `/usr/share/cargo/registry/curl-0.4.12/target/release/deps/post-da5f544df6f24574`

running 3 tests
thread '<unnamed>' panicked at 'thread 'unexpected header: "--------------------------ecd865f616614b4d\r\n" (remaining headers {"Expect: 100-continue\r\n"})<unnamed>', ' panicked at 'tests/server/mod.rsunexpected header: "--------------------------64cbe2ce926d5433\r\n" (remaining headers {"Expect: 100-continue\r\n"}):', 64thread 'tests/server/mod.rs:<unnamed>:21' panicked at '64
unexpected header: "--------------------------daf0bab0c6d19fa2\r\n" (remaining headers {"Expect: 100-continue\r\n"}):note: Run with `RUST_BACKTRACE=1` for a backtrace.
', 21tests/server/mod.rs
:64:21
test buffer ... FAILED
test file ... FAILED
test custom ... FAILED

failures:

---- buffer stdout ----
	thread 'buffer' panicked at 'handle.perform() failed with Error { description: "Server returned nothing (no headers, no data)", code: 52, extra: Some("Empty reply from server") }', tests/post.rs:77:5
child server thread also failed: Any

---- file stdout ----
	thread 'file' panicked at 'handle.perform() failed with Error { description: "Server returned nothing (no headers, no data)", code: 52, extra: Some("Empty reply from server") }', tests/post.rs:108:5
child server thread also failed: Any

---- custom stdout ----
	thread 'custom' panicked at 'handle.perform() failed with Error { description: "Server returned nothing (no headers, no data)", code: 52, extra: Some("Empty reply from server") }', tests/post.rs:47:5
child server thread also failed: Any


failures:
    buffer
    custom
    file

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests curl
     Running `/usr/bin/rustdoc --test /usr/share/cargo/registry/curl-0.4.12/src/lib.rs --crate-name curl -L dependency=/usr/share/cargo/registry/curl-0.4.12/target/release/deps -L native=/usr/lib64 -L dependency=/usr/share/cargo/registry/curl-0.4.12/target/release/deps --extern socket2=/usr/share/cargo/registry/curl-0.4.12/target/release/deps/libsocket2-5d5fc66f95f00231.rlib --extern mio=/usr/share/cargo/registry/curl-0.4.12/target/release/deps/libmio-4fd686a6d3556c94.rlib --extern libc=/usr/share/cargo/registry/curl-0.4.12/target/release/deps/liblibc-3f73e0a09b217b6c.rlib --extern mio_extras=/usr/share/cargo/registry/curl-0.4.12/target/release/deps/libmio_extras-3d4f071e0013c711.rlib --extern curl_sys=/usr/share/cargo/registry/curl-0.4.12/target/release/deps/libcurl_sys-683d675f4d4353c5.rlib --extern openssl_sys=/usr/share/cargo/registry/curl-0.4.12/target/release/deps/libopenssl_sys-bfd31ddec92a2b78.rlib --extern curl=/usr/share/cargo/registry/curl-0.4.12/target/release/deps/libcurl-a5e017f8670a0f1c.rlib --extern openssl_probe=/usr/share/cargo/registry/curl-0.4.12/target/release/deps/libopenssl_probe-f3d887c72cbee778.rlib`

running 15 tests
test src/lib.rs -  (line 18) ... ok
test src/easy/handle.rs - easy::handle::Easy::read_function (line 290) ... ok
test src/easy/handle.rs - easy::handle::Easy::read_function (line 275) ... ok
test src/multi.rs - multi::Multi::wait (line 485) ... ok
test src/easy/handle.rs - easy::handle::Easy (line 34) ... ok
test src/easy/handler.rs - easy::handler::Easy2<H>::resolve (line 1732) ... FAILED
test src/easy/handle.rs - easy::handle::Easy::header_function (line 483) ... ok
test src/easy/handler.rs - easy::handler::Easy2<H>::http_headers (line 1257) ... ok
test src/easy/handle.rs - easy::handle::Easy (line 58) ... ok
test src/easy/handle.rs - easy::handle::Easy::header_function (line 499) ... ok
test src/easy/handle.rs - easy::handle::Easy::write_function (line 219) ... ok
test src/easy/handle.rs - easy::handle::Easy (line 42) ... ok
test src/easy/handle.rs - easy::handle::Easy::write_function (line 205) ... ok
test src/easy/handler.rs - easy::handler::Handler (line 31) ... ok
test src/easy/handler.rs - easy::handler::Easy2 (line 358) ... ok

failures:

---- src/easy/handler.rs - easy::handler::Easy2<H>::resolve (line 1732) stdout ----
	thread 'src/easy/handler.rs - easy::handler::Easy2<H>::resolve (line 1732)' panicked at 'test executable failed:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { description: "Peer certificate cannot be authenticated with given CA certificates", code: 60, extra: Some("SSL certificate problem: certificate has expired") }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

', librustdoc/test.rs:356:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    src/easy/handler.rs - easy::handler::Easy2<H>::resolve (line 1732)

test result: FAILED. 14 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by alexcrichton** [comment]
I'm going to close this since it looks like an issue with the test environment, not these tests.
