### ISSUE TITLE
curl-sys 0.4.35+curl-7.71.1 crate missing curl folder

### ISSUE THREAD

**Issue by tarkah** [alexcrichton/curl-rust#352]
I'm getting the following error with the latest `curl-sys` release. When I download the crate from https://crates.io/api/v1/crates/curl-sys/0.4.35+curl-7.71.1/download, I notice the `curl` folder is missing.

```
error: failed to run custom build command for `curl-sys v0.4.35+curl-7.71.1`

Caused by:
  process didn't exit successfully: `/home/tarkah/projects/rust/tickrs/target/debug/build/curl-sys-b2c341e77fa5e3ae/build-script-build` (exit code: 101)
--- stdout
cargo:root=/home/tarkah/projects/rust/tickrs/target/debug/build/curl-sys-6e6b97968d6d9e35/out
cargo:include=/home/tarkah/projects/rust/tickrs/target/debug/build/curl-sys-6e6b97968d6d9e35/out/include
cargo:static=1

--- stderr
fatal: not a git repository (or any of the parent directories): .git
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/tarkah/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.4.35+curl-7.71.1/build.rs:68:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by baoyachi** [comment]
me too error
```bash
Couldn't find libcurl from pkgconfig (Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libcurl\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package libcurl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libcurl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libcurl\' found\n" } }), compiling it from source...
cargo:root=/home/gitlab-runner/builds/HKJF2qHZ/0/access/target/debug/build/curl-sys-e3850fbe7f5c4710/out
cargo:include=/home/gitlab-runner/builds/HKJF2qHZ/0/access/target/debug/build/curl-sys-e3850fbe7f5c4710/out/include
cargo:static=1

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by baoyachi** [comment]
@tarkah 
use dependencies
```toml
[dependencies]
curl-sys = "=0.4.34+curl-7.71.1"

```

**Comment by sagebind** [comment]
Looks like the latest version wasn't packaged correctly with the submodules checked out. I'll push out a new version ASAP.

**Comment by sagebind** [comment]
OK, newly published version should be packaged correctly. Give `curl 0.4.33` / `curl-sys 0.4.36+curl-7.71.1` a try.

**Comment by sagebind** [comment]
I've yanked `curl-sys` `0.4.35+curl-7.71.1`, so it should no longer be automatically selected for builds that don't explicitly reference it.

**Comment by alexcrichton** [comment]
Oops, sorry about this!
